const DATABASE_URI = process.env.DATABASE_URI;
const DB_NAME = 'e-com';
const ACCESS_TOKEN_SECRET = process.env.ACCESS_TOKEN_SECRET;
const REFRESH_TOKEN_SECRET = process.env.REFRESH_TOKEN_SECRET;

export { DATABASE_URI, DB_NAME, ACCESS_TOKEN_SECRET, REFRESH_TOKEN_SECRET };
